services:
    app:
        build:
            context: .
            target: dev
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./:/app:cached
        depends_on:
            - redis
    redis:
        image: redis:7-alpine
        restart: unless-stopped
