services:
    app:
        build:
            context: .
            target: prod
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "1024M"
